"""add deliveries table

Revision ID: 57770ade9f17
Revises: 9692e85f15ab
Create Date: 2026-09-05 15:05:35.692509

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57770ade9f17"
down_revision: Union[str, Sequence[str], None] = "9692e85f15ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "deliveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("location", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "bank_account_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("items", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_deliveries_invoice_id"), "deliveries", ["invoice_id"], unique=False
    )
    op.create_index(
        op.f("ix_deliveries_user_id"), "deliveries", ["user_id"], unique=False
    )
    op.drop_index(op.f("ix_saved_systems_user_id"), table_name="saved_systems")
    op.drop_table("saved_systems")
    op.drop_index(op.f("ix_accounts_email"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_username"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_constraint("order_items_order_id_fkey", "order_items", type_="foreignkey")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.create_foreign_key(None, "cart_items", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "cart_items", "product", ["product_id"], ["id"])
    op.create_foreign_key(None, "favorites", "product", ["product_id"], ["id"])
    op.create_foreign_key(None, "favorites", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "passwordresettoken", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "sessions", "users", ["user_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.drop_constraint(None, "passwordresettoken", type_="foreignkey")
    op.drop_constraint(None, "favorites", type_="foreignkey")
    op.drop_constraint(None, "favorites", type_="foreignkey")
    op.drop_constraint(None, "cart_items", type_="foreignkey")
    op.drop_constraint(None, "cart_items", type_="foreignkey")
    op.create_table(
        "order_items",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "unit_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("order_items_order_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("order_items_pkey")),
    )
    op.create_index(
        op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING", "PROCESSING", "COMPLETED", "CANCELLED", name="orderstatus"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "total",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("orders_pkey")),
    )
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_table(
        "accounts",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("phone", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("password_hash", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("accounts_pkey")),
    )
    op.create_index(op.f("ix_accounts_username"), "accounts", ["username"], unique=True)
    op.create_index(op.f("ix_accounts_email"), "accounts", ["email"], unique=True)
    op.create_table(
        "saved_systems",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("in_cart", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "configuration",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "total_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "estimated_daily_wh",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "estimated_peak_w",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("saved_systems_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("saved_systems_pkey")),
    )
    op.create_index(
        op.f("ix_saved_systems_user_id"), "saved_systems", ["user_id"], unique=False
    )
    op.drop_index(op.f("ix_deliveries_user_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_invoice_id"), table_name="deliveries")
    op.drop_table("deliveries")
    # ### end Alembic commands ###
